secret: dongtaiwang.com
mixed-port: 7890
allow-lan: false
log-level: info
dns:
  enabled: true
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
proxies:
  - name: dongtaiwang.com_0
    type: hysteria
    server: 51.15.10.149
    port: 36474
    ports: 40000-50000
    auth_str: dongtaiwang.com
    alpn:
      - h3
    sni: www.bing.com
    skip-cert-verify: true
    up: "11 Mbps"
    down: "55 Mbps"
  - name: dongtaiwang.com_1                     
    type: vmess
    server: 104.21.238.120
    port: 443
    uuid: 2c15ec31-54f6-4cc7-aa9b-e906c6889bab
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    servername: xray2.6016725.xyz
    network: ws
    ws-opts:
      path: github.com/Alvin9999
      headers:
        Host: xray2.6016725.xyz
      early-data-header-name: Sec-WebSocket-Protocol
      v2ray-http-upgrade: true
      v2ray-http-upgrade-fast-open: true
  - name: dongtaiwang.com_2                    
    type: vmess
    server: 104.18.114.190
    port: 443
    uuid: 2c15ec31-54f6-4cc7-aa9b-e906c6889bab
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    servername: xray2.6016725.xyz
    network: ws
    ws-opts:
      path: github.com/Alvin9999
      headers:
        Host: xray2.6016725.xyz
      early-data-header-name: Sec-WebSocket-Protocol
      v2ray-http-upgrade: true
      v2ray-http-upgrade-fast-open: true
  - name: dongtaiwang.com_3                     
    type: vmess
    server: 104.18.114.191
    port: 443
    uuid: 2c15ec31-54f6-4cc7-aa9b-e906c6889bab
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    servername: xray2.6016725.xyz
    network: ws
    ws-opts:
      path: github.com/Alvin9999
      headers:
        Host: xray2.6016725.xyz
      early-data-header-name: Sec-WebSocket-Protocol
      v2ray-http-upgrade: true
      v2ray-http-upgrade-fast-open: true
  - name: dongtaiwang.com_4                     
    type: vmess
    server: 162.159.45.59
    port: 443
    uuid: 2c15ec31-54f6-4cc7-aa9b-e906c6889bab
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    servername: xray2.6016725.xyz
    network: ws
    ws-opts:
      path: github.com/Alvin9999
      headers:
        Host: xray2.6016725.xyz
      early-data-header-name: Sec-WebSocket-Protocol
      v2ray-http-upgrade: true
      v2ray-http-upgrade-fast-open: true
  - name: dongtaiwang.com_5                     
    type: vmess
    server: 162.159.45.60
    port: 443
    uuid: 2c15ec31-54f6-4cc7-aa9b-e906c6889bab
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    servername: xray2.6016725.xyz
    network: ws
    ws-opts:
      path: github.com/Alvin9999
      headers:
        Host: xray2.6016725.xyz
      early-data-header-name: Sec-WebSocket-Protocol
      v2ray-http-upgrade: true
      v2ray-http-upgrade-fast-open: true
  - name: dongtaiwang.com_6                    
    type: vmess
    server: 104.26.5.107
    port: 443
    uuid: 2c15ec31-54f6-4cc7-aa9b-e906c6889bab
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    servername: xray2.6016725.xyz
    network: ws
    ws-opts:
      path: github.com/Alvin9999
      headers:
        Host: xray2.6016725.xyz
      early-data-header-name: Sec-WebSocket-Protocol
      v2ray-http-upgrade: true
      v2ray-http-upgrade-fast-open: true
  - name: dongtaiwang.com_7                   
    type: vmess
    server: 104.26.5.108
    port: 443
    uuid: 2c15ec31-54f6-4cc7-aa9b-e906c6889bab
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    servername: xray2.6016725.xyz
    network: ws
    ws-opts:
      path: github.com/Alvin9999
      headers:
        Host: xray2.6016725.xyz
      early-data-header-name: Sec-WebSocket-Protocol
      v2ray-http-upgrade: true
      v2ray-http-upgrade-fast-open: true
  - name: dongtaiwang.com_8                    
    type: vmess
    server: 172.64.96.184
    port: 443
    uuid: 2c15ec31-54f6-4cc7-aa9b-e906c6889bab
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    servername: xray2.6016725.xyz
    network: ws
    ws-opts:
      path: github.com/Alvin9999
      headers:
        Host: xray2.6016725.xyz
      early-data-header-name: Sec-WebSocket-Protocol
      v2ray-http-upgrade: true
      v2ray-http-upgrade-fast-open: true
  - name: dongtaiwang.com_9                    
    type: vmess
    server: 172.64.96.185
    port: 443
    uuid: 2c15ec31-54f6-4cc7-aa9b-e906c6889bab
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    servername: xray2.6016725.xyz
    network: ws
    ws-opts:
      path: github.com/Alvin9999
      headers:
        Host: xray2.6016725.xyz
      early-data-header-name: Sec-WebSocket-Protocol
      v2ray-http-upgrade: true
      v2ray-http-upgrade-fast-open: true
proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - DIRECT
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
      - dongtaiwang.com_5
      - dongtaiwang.com_6
      - dongtaiwang.com_7
      - dongtaiwang.com_8
      - dongtaiwang.com_9
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
      - dongtaiwang.com_5
      - dongtaiwang.com_6
      - dongtaiwang.com_7
      - dongtaiwang.com_8
      - dongtaiwang.com_9
  - name: ğŸŒ å›½å¤–åª’ä½“
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
      - dongtaiwang.com_5
      - dongtaiwang.com_6
      - dongtaiwang.com_7
      - dongtaiwang.com_8
      - dongtaiwang.com_9
  - name: ğŸ“² ç”µæŠ¥ä¿¡æ¯
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
      - dongtaiwang.com_5
      - dongtaiwang.com_6
      - dongtaiwang.com_7
      - dongtaiwang.com_8
      - dongtaiwang.com_9
  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    type: select
    proxies:
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
      - dongtaiwang.com_5
      - dongtaiwang.com_6
      - dongtaiwang.com_7
      - dongtaiwang.com_8
      - dongtaiwang.com_9
  - name: ğŸ è‹¹æœæœåŠ¡
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
      - dongtaiwang.com_5
      - dongtaiwang.com_6
      - dongtaiwang.com_7
      - dongtaiwang.com_8
      - dongtaiwang.com_9
  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: ğŸ›‘ å…¨çƒæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸƒ åº”ç”¨å‡€åŒ–
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
      - dongtaiwang.com_5
      - dongtaiwang.com_6
      - dongtaiwang.com_7
      - dongtaiwang.com_8
      - dongtaiwang.com_9
rules:
  - MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
