port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_1,
      server: cf-lt.sharecentre.online,
      port: 80,
      type: vmess,
      uuid: 2d5d8b9c-8ec4-4a37-b610-78e71e13eaef,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /shirker, headers: { Host: ca.ilovescp.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_2,
      server: zfc.windowsupdate1.com,
      port: 443,
      type: vmess,
      uuid: 2cb6537c-e6db-4d20-ba70-3495b95aca68,
      alterId: 0,
      cipher: auto,
      tls: true,
      network: ws,
      ws-opts: { path: /kbjc/de1, headers: { Host: de1.hnokkdf.top } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_3,
      server: zfc.windowsupdate1.com,
      port: 443,
      type: vmess,
      uuid: 2cb6537c-e6db-4d20-ba70-3495b95aca68,
      alterId: 0,
      cipher: auto,
      tls: true,
      network: ws,
      ws-opts: { path: /kbjc/us4, headers: { Host: us4.hnokkdf.top } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_4,
      server: zfc.windowsupdate1.com,
      port: 443,
      type: vmess,
      uuid: 2cb6537c-e6db-4d20-ba70-3495b95aca68,
      alterId: 0,
      cipher: auto,
      tls: true,
      network: ws,
      ws-opts: { path: /kbjc/fr1, headers: { Host: fr1.hnokkdf.top } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_5,
      server: cf-lt.sharecentre.online,
      port: 80,
      type: vmess,
      uuid: 2d5d8b9c-8ec4-4a37-b610-78e71e13eaef,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /shirker, headers: { Host: lv1.sharecentrepro.org } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_6,
      server: sw.tbstbstbstbs666.com,
      port: 18820,
      type: vmess,
      uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: sw.tbstbstbstbs666.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_7,
      server: sw.tbstbstbstbs666.com,
      port: 18805,
      type: vmess,
      uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: sw.tbstbstbstbs666.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_8,
      server: sw.tbstbstbstbs666.com,
      port: 18805,
      type: vmess,
      uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: sw.tbstbstbstbs666.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_9,
      server: sw.tbstbstbstbs666.com,
      port: 18805,
      type: vmess,
      uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: sw.tbstbstbstbs666.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_10,
      server: sw.tbstbstbstbs666.com,
      port: 18807,
      type: vmess,
      uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: sw.tbstbstbstbs666.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_11,
      server: cfef591a-4e4b-b8da-96c5-ac03d90ee2e6.cnnic.rip,
      port: 80,
      type: vmess,
      uuid: 070bd7d4-bd37-4929-8efa-c01107cc12a5,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: tms.dingtalk.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_12,
      server: sw.tbstbstbstbs666.com,
      port: 18823,
      type: vmess,
      uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: sw.tbstbstbstbs666.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_13,
      server: sw.tbstbstbstbs666.com,
      port: 18807,
      type: vmess,
      uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: sw.tbstbstbstbs666.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_14,
      server: sw.tbstbstbstbs666.com,
      port: 18834,
      type: vmess,
      uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: sw.tbstbstbstbs666.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_15,
      server: sw.tbstbstbstbs666.com,
      port: 18834,
      type: vmess,
      uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: sw.tbstbstbstbs666.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_16,
      server: sw.tbstbstbstbs666.com,
      port: 18807,
      type: vmess,
      uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: sw.tbstbstbstbs666.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_17,
      server: zfc.windowsupdate1.com,
      port: 443,
      type: vmess,
      uuid: 2cb6537c-e6db-4d20-ba70-3495b95aca68,
      alterId: 0,
      cipher: auto,
      tls: true,
      network: ws,
      ws-opts: { path: /kbjc/jp1, headers: { Host: jp1.hnokkdf.top } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_18,
      server: sw.tbstbstbstbs666.com,
      port: 18812,
      type: vmess,
      uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: sw.tbstbstbstbs666.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_19,
      server: jp80.fee68414a14e.sanfen004.me,
      port: 80,
      type: vmess,
      uuid: 74976c4a-1e9f-4e4a-b495-bd94c938ae9b,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /zh-cn, headers: { Host: www.baidu.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_20,
      server: 140.249.204.236,
      port: 46794,
      type: vmess,
      uuid: 070bd7d4-bd37-4929-8efa-c01107cc12a5,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: tms.dingtalk.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_21,
      server: hk80.8b750e3e20aa.sanfen004.me,
      port: 80,
      type: vmess,
      uuid: 74976c4a-1e9f-4e4a-b495-bd94c938ae9b,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /zh-cn/, headers: { Host: www.baidu.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_22,
      server: 8.219.216.27,
      port: 2052,
      type: vmess,
      uuid: 8ed9aec2-e02e-4a27-fe02-c3e20452e4c7,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: h4.mamadcucu.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_23,
      server: cf-lt.sharecentre.online,
      port: 80,
      type: vmess,
      uuid: 2d5d8b9c-8ec4-4a37-b610-78e71e13eaef,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /shirker, headers: { Host: dp3.scproxy.top } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_24,
      server: cf-lt.sharecentre.online,
      port: 80,
      type: vmess,
      uuid: 2d5d8b9c-8ec4-4a37-b610-78e71e13eaef,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /shirker, headers: { Host: uk1.scproxy.top } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_25,
      server: cf-lt.sharecentre.online,
      port: 80,
      type: vmess,
      uuid: 2d5d8b9c-8ec4-4a37-b610-78e71e13eaef,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /shirker, headers: { Host: hk-hytron.ilovescp.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_26,
      server: cf-lt.sharecentre.online,
      port: 80,
      type: vmess,
      uuid: 2d5d8b9c-8ec4-4a37-b610-78e71e13eaef,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /shirker, headers: { Host: dp2.scproxy.top } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_27,
      server: m.lwvzmdu.cn,
      port: 16635,
      type: vmess,
      uuid: ad3f9bf7-d8d1-47df-a6bd-77ff50037339,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: m.lwvzmdu.cn } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_28,
      server: t.cccao.cyou,
      port: 16635,
      type: vmess,
      uuid: ad3f9bf7-d8d1-47df-a6bd-77ff50037339,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: t.cccao.cyou } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_29,
      server: t.cccao.cyou,
      port: 16635,
      type: vmess,
      uuid: ad3f9bf7-d8d1-47df-a6bd-77ff50037339,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: t.cccao.cyou } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_30,
      server: sw.tbstbstbstbs666.com,
      port: 18829,
      type: vmess,
      uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: sw.tbstbstbstbs666.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_31,
      server: sw.tbstbstbstbs666.com,
      port: 18839,
      type: vmess,
      uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: sw.tbstbstbstbs666.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_32,
      server: cf-lt.sharecentre.online,
      port: 80,
      type: vmess,
      uuid: 2d5d8b9c-8ec4-4a37-b610-78e71e13eaef,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /shirker, headers: { Host: dp4.scproxy.top } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_33,
      server: cf-lt.sharecentre.online,
      port: 80,
      type: vmess,
      uuid: 2d5d8b9c-8ec4-4a37-b610-78e71e13eaef,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /shirker, headers: { Host: lv2.sharecentrepro.org } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_34,
      server: cf-lt.sharecentre.online,
      port: 80,
      type: vmess,
      uuid: 2d5d8b9c-8ec4-4a37-b610-78e71e13eaef,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /shirker, headers: { Host: jp.scproxy.top } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_35,
      server: cf-lt.sharecentre.online,
      port: 80,
      type: vmess,
      uuid: 2d5d8b9c-8ec4-4a37-b610-78e71e13eaef,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /shirker, headers: { Host: do.sharecentrepro.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_36,
      server: cf-lt.sharecentre.online,
      port: 80,
      type: vmess,
      uuid: 2d5d8b9c-8ec4-4a37-b610-78e71e13eaef,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /shirker, headers: { Host: dp1.scproxy.top } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_37,
      server: cf-lt.sharecentre.online,
      port: 80,
      type: vmess,
      uuid: 2d5d8b9c-8ec4-4a37-b610-78e71e13eaef,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /shirker, headers: { Host: fr.sharecentrepro.org } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_38,
      server: cf-lt.sharecentre.online,
      port: 80,
      type: vmess,
      uuid: 2d5d8b9c-8ec4-4a37-b610-78e71e13eaef,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /shirker, headers: { Host: de1.sharecentrepro.org } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_39,
      server: zfc.windowsupdate1.com,
      port: 443,
      type: vmess,
      uuid: 2cb6537c-e6db-4d20-ba70-3495b95aca68,
      alterId: 0,
      cipher: auto,
      tls: true,
      network: ws,
      ws-opts: { path: /kbjc/us2, headers: { Host: us2.hnokkdf.top } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_40,
      server: sw.tbstbstbstbs666.com,
      port: 18831,
      type: vmess,
      uuid: 572690b3-7120-3b41-8fb7-070defaae755,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: sw.tbstbstbstbs666.com } },
    }
  - {
      name: https://github.com/Alvin9999/new-pac/wiki_41,
      server: sw.tbstbstbstbs666.com,
      port: 18831,
      type: vmess,
      uuid: 572690b3-7120-3b41-8fb7-070defaae755,
      alterId: 0,
      cipher: auto,
      tls: false,
      network: ws,
      ws-opts: { path: /, headers: { Host: sw.tbstbstbstbs666.com } },
    }
proxy-groups:
  - name: üî∞ ËäÇÁÇπÈÄâÊã©
    type: select
    proxies:
      - ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  - name: ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - https://github.com/Alvin9999/new-pac/wiki_1
      - https://github.com/Alvin9999/new-pac/wiki_2
      - https://github.com/Alvin9999/new-pac/wiki_3
      - https://github.com/Alvin9999/new-pac/wiki_4
      - https://github.com/Alvin9999/new-pac/wiki_5
      - https://github.com/Alvin9999/new-pac/wiki_6
      - https://github.com/Alvin9999/new-pac/wiki_7
      - https://github.com/Alvin9999/new-pac/wiki_8
      - https://github.com/Alvin9999/new-pac/wiki_9
      - https://github.com/Alvin9999/new-pac/wiki_10
      - https://github.com/Alvin9999/new-pac/wiki_11
      - https://github.com/Alvin9999/new-pac/wiki_12
      - https://github.com/Alvin9999/new-pac/wiki_13
      - https://github.com/Alvin9999/new-pac/wiki_14
      - https://github.com/Alvin9999/new-pac/wiki_15
      - https://github.com/Alvin9999/new-pac/wiki_16
      - https://github.com/Alvin9999/new-pac/wiki_17
      - https://github.com/Alvin9999/new-pac/wiki_18
      - https://github.com/Alvin9999/new-pac/wiki_19
      - https://github.com/Alvin9999/new-pac/wiki_20
      - https://github.com/Alvin9999/new-pac/wiki_21
      - https://github.com/Alvin9999/new-pac/wiki_22
      - https://github.com/Alvin9999/new-pac/wiki_23
      - https://github.com/Alvin9999/new-pac/wiki_24
      - https://github.com/Alvin9999/new-pac/wiki_25
      - https://github.com/Alvin9999/new-pac/wiki_26
      - https://github.com/Alvin9999/new-pac/wiki_27
      - https://github.com/Alvin9999/new-pac/wiki_28
      - https://github.com/Alvin9999/new-pac/wiki_29
      - https://github.com/Alvin9999/new-pac/wiki_30
      - https://github.com/Alvin9999/new-pac/wiki_31
      - https://github.com/Alvin9999/new-pac/wiki_32
      - https://github.com/Alvin9999/new-pac/wiki_33
      - https://github.com/Alvin9999/new-pac/wiki_34
      - https://github.com/Alvin9999/new-pac/wiki_35
      - https://github.com/Alvin9999/new-pac/wiki_36
      - https://github.com/Alvin9999/new-pac/wiki_37
      - https://github.com/Alvin9999/new-pac/wiki_38
      - https://github.com/Alvin9999/new-pac/wiki_39
      - https://github.com/Alvin9999/new-pac/wiki_40
      - https://github.com/Alvin9999/new-pac/wiki_41
rules:
  - MATCH,üî∞ ËäÇÁÇπÈÄâÊã©
