port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: https://github.com/Alvin9999/new-pac/wiki_1, server: sw.tbstbstbstbs666.com, port: 18839, type: vmess, uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: sw.tbstbstbstbs666.com}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki_2, server: sw.tbstbstbstbs666.com, port: 18812, type: vmess, uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: sw.tbstbstbstbs666.com}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki_3, server: sw.tbstbstbstbs666.com, port: 18820, type: vmess, uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: sw.tbstbstbstbs666.com}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki_4, server: sw.tbstbstbstbs666.com, port: 18829, type: vmess, uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: sw.tbstbstbstbs666.com}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki_5, server: zfc.windowsupdate1.com, port: 443, type: vmess, uuid: 9ffa0a0c-1d88-4683-9efe-7c3893a4bb87, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: /kbjc/us3, headers: {Host: us3.hnokkdf.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki_6, server: cf.yxjnode.com, port: 80, type: vmess, uuid: 09c1d32d-4458-4ebf-b36d-4dd732bae3aa, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /yxzbp, headers: {Host: dp2.yxjnode.com}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki_7, server: sw.tbstbstbstbs666.com, port: 18823, type: vmess, uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: sw.tbstbstbstbs666.com}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki_8, server: zfc.windowsupdate1.com, port: 443, type: vmess, uuid: 9ffa0a0c-1d88-4683-9efe-7c3893a4bb87, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: /kbjc/us4, headers: {Host: us4.hnokkdf.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki_9, server: cf.yxjnode.com, port: 80, type: vmess, uuid: 09c1d32d-4458-4ebf-b36d-4dd732bae3aa, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /yxzbp, headers: {Host: buyvm2.yxjnode.com}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki_10, server: zfc.windowsupdate1.com, port: 443, type: vmess, uuid: 9ffa0a0c-1d88-4683-9efe-7c3893a4bb87, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: /kbjc/us2, headers: {Host: us2.hnokkdf.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki_11, server: zfc.windowsupdate1.com, port: 443, type: vmess, uuid: 9ffa0a0c-1d88-4683-9efe-7c3893a4bb87, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: /kbjc/fr1, headers: {Host: fr1.hnokkdf.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki_12, server: 59.36.84.180, port: 63092, type: vmess, uuid: 311f3c4b-90a1-3c5c-a4fe-215cc7c90d02, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: 59.36.84.180}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki_13, server: cf.yxjnode.com, port: 80, type: vmess, uuid: 09c1d32d-4458-4ebf-b36d-4dd732bae3aa, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /yxzbp, headers: {Host: dp3.yxjnode.com}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki_14, server: z82.topzz.cc, port: 44332, type: vmess, uuid: d2a1cd29-9ac2-3165-a082-cf09cdd3bf50, alterId: 0, cipher: auto, tls: true}
  - {name: https://github.com/Alvin9999/new-pac/wiki_15, server: z82.topzz.cc, port: 44332, type: vmess, uuid: d2a1cd29-9ac2-3165-a082-cf09cdd3bf50, alterId: 0, cipher: auto, tls: true}
  - {name: https://github.com/Alvin9999/new-pac/wiki_16, server: ovocloud.xyz, port: 58893, type: ss, cipher: chacha20-ietf-poly1305, password: 4152b86e-952d-414a-b772-6be5c90f35e5}
  - {name: https://github.com/Alvin9999/new-pac/wiki_17, server: ovocloud.xyz, port: 58894, type: ss, cipher: chacha20-ietf-poly1305, password: 4152b86e-952d-414a-b772-6be5c90f35e5}
  - {name: https://github.com/Alvin9999/new-pac/wiki_18, server: ovocloud.xyz, port: 58905, type: ss, cipher: chacha20-ietf-poly1305, password: 4152b86e-952d-414a-b772-6be5c90f35e5}
  - {name: https://github.com/Alvin9999/new-pac/wiki_19, server: ovocloud.xyz, port: 58898, type: ss, cipher: chacha20-ietf-poly1305, password: 4152b86e-952d-414a-b772-6be5c90f35e5}
  - {name: https://github.com/Alvin9999/new-pac/wiki_20, server: ovocloud.xyz, port: 58897, type: ss, cipher: chacha20-ietf-poly1305, password: 4152b86e-952d-414a-b772-6be5c90f35e5}
  - {name: https://github.com/Alvin9999/new-pac/wiki_21, server: ovocloud.xyz, port: 58887, type: ss, cipher: chacha20-ietf-poly1305, password: 4152b86e-952d-414a-b772-6be5c90f35e5}
  - {name: https://github.com/Alvin9999/new-pac/wiki_22, server: ovocloud.xyz, port: 58888, type: ss, cipher: chacha20-ietf-poly1305, password: 4152b86e-952d-414a-b772-6be5c90f35e5}
  - {name: https://github.com/Alvin9999/new-pac/wiki_23, server: ovocloud.xyz, port: 58885, type: ss, cipher: chacha20-ietf-poly1305, password: 4152b86e-952d-414a-b772-6be5c90f35e5}
  - {name: https://github.com/Alvin9999/new-pac/wiki_24, server: ovocloud.xyz, port: 58884, type: ss, cipher: chacha20-ietf-poly1305, password: 4152b86e-952d-414a-b772-6be5c90f35e5}
  - {name: https://github.com/Alvin9999/new-pac/wiki_25, server: ovocloud.xyz, port: 58881, type: ss, cipher: chacha20-ietf-poly1305, password: 4152b86e-952d-414a-b772-6be5c90f35e5}
  - {name: https://github.com/Alvin9999/new-pac/wiki_26, server: ovocloud.xyz, port: 58891, type: ss, cipher: chacha20-ietf-poly1305, password: 4152b86e-952d-414a-b772-6be5c90f35e5}
  - {name: https://github.com/Alvin9999/new-pac/wiki_27, server: ovocloud.xyz, port: 58882, type: ss, cipher: chacha20-ietf-poly1305, password: 4152b86e-952d-414a-b772-6be5c90f35e5}
  - {name: https://github.com/Alvin9999/new-pac/wiki_28, server: ovocloud.xyz, port: 58883, type: ss, cipher: chacha20-ietf-poly1305, password: 4152b86e-952d-414a-b772-6be5c90f35e5}
  - {name: https://github.com/Alvin9999/new-pac/wiki_29, server: ovocloud.xyz, port: 58892, type: ss, cipher: chacha20-ietf-poly1305, password: 4152b86e-952d-414a-b772-6be5c90f35e5}
  - {name: https://github.com/Alvin9999/new-pac/wiki_30, server: ovocloud.xyz, port: 58886, type: ss, cipher: chacha20-ietf-poly1305, password: 4152b86e-952d-414a-b772-6be5c90f35e5}
  - {name: https://github.com/Alvin9999/new-pac/wiki_31, server: ovocloud.xyz, port: 58906, type: ss, cipher: chacha20-ietf-poly1305, password: 4152b86e-952d-414a-b772-6be5c90f35e5}
  - {name: https://github.com/Alvin9999/new-pac/wiki_32, server: ahcm.v-too.cloud, port: 10259, type: ss, cipher: chacha20-ietf-poly1305, password: 75c9c41d-5287-4b13-abe4-c66a8c0ab9f4}
  - {name: https://github.com/Alvin9999/new-pac/wiki_33, server: wj-jp-02-01.wujie.bio, port: 9306, type: ss, cipher: chacha20-ietf-poly1305, password: 4b89f977-b22c-4d8a-bdaf-4c5e1b2acb15}
  - {name: https://github.com/Alvin9999/new-pac/wiki_34, server: wj-jp-02-01.wujie.bio, port: 9306, type: ss, cipher: chacha20-ietf-poly1305, password: 2f1831cc-4c25-4adc-b340-e3e5de09a7d3}
proxy-groups:
  - name: üî∞ ËäÇÁÇπÈÄâÊã©
    type: select
    proxies:
      - ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  - name: ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - https://github.com/Alvin9999/new-pac/wiki_1
      - https://github.com/Alvin9999/new-pac/wiki_2
      - https://github.com/Alvin9999/new-pac/wiki_3
      - https://github.com/Alvin9999/new-pac/wiki_4
      - https://github.com/Alvin9999/new-pac/wiki_5
      - https://github.com/Alvin9999/new-pac/wiki_6
      - https://github.com/Alvin9999/new-pac/wiki_7
      - https://github.com/Alvin9999/new-pac/wiki_8
      - https://github.com/Alvin9999/new-pac/wiki_9
      - https://github.com/Alvin9999/new-pac/wiki_10
      - https://github.com/Alvin9999/new-pac/wiki_11
      - https://github.com/Alvin9999/new-pac/wiki_12
      - https://github.com/Alvin9999/new-pac/wiki_13
      - https://github.com/Alvin9999/new-pac/wiki_14
      - https://github.com/Alvin9999/new-pac/wiki_15
      - https://github.com/Alvin9999/new-pac/wiki_16
      - https://github.com/Alvin9999/new-pac/wiki_17
      - https://github.com/Alvin9999/new-pac/wiki_18
      - https://github.com/Alvin9999/new-pac/wiki_19
      - https://github.com/Alvin9999/new-pac/wiki_20
      - https://github.com/Alvin9999/new-pac/wiki_21
      - https://github.com/Alvin9999/new-pac/wiki_22
      - https://github.com/Alvin9999/new-pac/wiki_23
      - https://github.com/Alvin9999/new-pac/wiki_24
      - https://github.com/Alvin9999/new-pac/wiki_25
      - https://github.com/Alvin9999/new-pac/wiki_26
      - https://github.com/Alvin9999/new-pac/wiki_27
      - https://github.com/Alvin9999/new-pac/wiki_28
      - https://github.com/Alvin9999/new-pac/wiki_29
      - https://github.com/Alvin9999/new-pac/wiki_30
      - https://github.com/Alvin9999/new-pac/wiki_31
      - https://github.com/Alvin9999/new-pac/wiki_32
      - https://github.com/Alvin9999/new-pac/wiki_33
      - https://github.com/Alvin9999/new-pac/wiki_34
rules:
 - MATCH,üî∞ ËäÇÁÇπÈÄâÊã©
